name: docdoc
description: "A new Flutter project."

publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  ## A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.11
  ## State Management.
  flutter_bloc: ^8.1.5
  ## Code Generator (Mainly used with cubit & retrofit).
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  ## Dependency Injection
  get_it: ^7.7.0
  ## Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  ## Networking
  dio: ^5.2.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1
  ## Localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  ## for splash screen
  flutter_native_splash: ^2.4.0
  ## An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.10+1
  ## for adapting screen and font size
  flutter_screenutil: ^5.9.3
  ## Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.3.0
  ## Flutter library to load and cache network images.
  cached_network_image: ^3.3.0
  


dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  ## dart run build_runner build --delete-conflicting-outputs

