default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:169917436261:android:80ff954afe477f4cfad18c",
      firebase_cli_token: "1//094KgRU8V-u9TCgYIARAAGAkSNwF-L9IrQlVzWmIrsX9ZwvaoMTb3hb9hOAa9FKCKsYxl9P4xa8mHE-Fy9dk1iwTjsrsKCFVZzLg",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "mohamed.essam900009@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
  )
  end
end
